#!/bin/bash

echo "🔍 DEBUG: Path Investigation"
echo "================================"
echo "SRCROOT: ${SRCROOT}"
echo "PWD: $(pwd)"
echo "Script location: ${BASH_SOURCE[0]}"
echo "Script directory: $(dirname ${BASH_SOURCE[0]})"
echo ""
echo "📁 Contents of SRCROOT:"
ls -la "${SRCROOT}"
echo ""
echo "📁 Contents of current directory:"
ls -la "$(pwd)"
echo ""
echo "🔍 Looking for test files:"
echo "In SRCROOT/Tests:"
ls -la "${SRCROOT}/Tests" 2>/dev/null || echo "❌ SRCROOT/Tests does not exist"
echo ""
echo "In SRCROOT/Source/Tests:"
ls -la "${SRCROOT}/Source/Tests" 2>/dev/null || echo "❌ SRCROOT/Source/Tests does not exist" 
echo ""
echo "In current directory:"
ls -la "./Tests" 2>/dev/null || echo "❌ ./Tests does not exist"
echo ""
echo "In parent directory:"
ls -la "../Tests" 2>/dev/null || echo "❌ ../Tests does not exist"
echo ""
echo "🔍 Find all run_critical_tests.sh files:"
find "${SRCROOT}" -name "run_critical_tests.sh" -type f 2>/dev/null || echo "❌ No test scripts found in SRCROOT"